# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "tungnt9905@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  

[Languages.vi]
title = "Bắt đầu với Amazon VPC và AWS VPN Site to Site"
weight = 2
languageName = "Tiếng Việt"


